// <copyright file="PexAssemblyInfo.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

using Microsoft.Pex.Framework.Instrumentation;
using Symb2;
using System.Runtime.CompilerServices;

[assembly: PexInstrumentAssembly("KellermanSoftware.Compare-NET-Objects")]
[assembly: PexInstrumentType(typeof(ConditionalWeakTable<object, RbId>))]
